/* Auto-generated by scripts/build_zh_site.py — Chinese overlay for timeline data */
window.ARXIVCOUNT_ZH = {
  "events": {
    "minerva": {
      "label": "Minerva（数学大模型）",
      "note": "面向定量推理的语言模型；仍以基准测试为主，尚未进入研究级证明。"
    },
    "chatgpt": {
      "label": "ChatGPT 公开发布",
      "note": "大规模采用开始；写作辅助与早期数学实验大量涌现。",
      "keystone_reason": "大众数学实验的公共大模型入口。"
    },
    "gpt4": {
      "label": "GPT-4 时代的数学演示",
      "note": "非形式化数学演示明显增强；对研究级断言仍不可靠。"
    },
    "alphageometry": {
      "label": "AlphaGeometry",
      "note": "奥赛几何；为后续研究系统提供神经—符号模板。",
      "keystone_reason": "奥赛级神经—符号里程碑。"
    },
    "alphaproof": {
      "label": "AlphaProof / IMO 级形式化证明",
      "note": "IMO 规模的形式化定理证明；Lean 成为验证骨干。",
      "keystone_reason": "形式化 IMO 级证明；Lean 作骨干。"
    },
    "lean_ai_wave": {
      "label": "Lean + LLM 研究向形式化浪潮",
      "note": "自动形式化 / 智能体式 Lean 开始出现研究邻域用途。",
      "keystone_reason": "研究邻域自动形式化浪潮的标志。"
    },
    "2509.18057": {
      "label": "AI 发现的小工具改进不可近似界",
      "note": "AlphaEvolve 自主搜索并发现新组合小工具与 Ramanujan 图，还演化出更快验证器，从而改进硬度结果。"
    },
    "2510.20013": {
      "label": "AI 发现开放问题的反例",
      "note": "GPT-5 Pro 在数值实验后提出特定布尔函数反例；作者手工验证并证明局部最优性定理。",
      "open_problem_name": "带擦除的 NICD 中 majority 最优性"
    },
    "2510.23513": {
      "label": "AI 辅助解决 NAG 点列收敛",
      "note": "ChatGPT 生成候选证明并最终给出连续时间情形的完整证明，再适配到离散 NAG。",
      "open_problem_name": "Nesterov 加速梯度法的点列收敛"
    },
    "2511.18828": {
      "label": "AI 辅助解决稳健统计中的开放问题",
      "note": "GPT-5 提出新技术（动态 Benamou–Brenier、更尖偏置界）并协助验证明，但正确性与补洞仍依赖人类专长。",
      "open_problem_name": "Wasserstein 污染下稳健密度估计的极小极大最优速率"
    },
    "2512.10220": {
      "label": "AI 解决学习曲线单调性开放问题",
      "note": "AI 生成全部证明（含主定理），并推广到高维与其他分布；人类负责提示与验证。",
      "open_problem_name": "MLE（高斯方差估计）学习曲线的单调性"
    },
    "formal_open_problems": {
      "label": "智能体 Lean / 开放问题形式化结果集群",
      "note": "2026 上半年 Erdős 问题与形式化 AI 证明成簇出现。"
    },
    "2601.07421": {
      "label": "首个 AI 自主解决 Erdős 问题的高可见写本",
      "note": "GPT-5.2 Pro 生成非形式论证；Aristotle 产出形式 Lean 证明；ChatGPT 协助写作与推广。",
      "keystone_reason": "早期高可见的 Erdős 问题 AI 解决写本。",
      "open_problem_name": "Erdős 问题 #728"
    },
    "2602.16807": {
      "label": "超立方体切片上界改进",
      "note": "CPro1 生成多样搜索算法并浮现结构约束（如相同初始列）；经人类综合后得到改进上界。",
      "open_problem_name": "超立方体切片问题（确定 S(n)）"
    },
    "2603.09680": {
      "label": "椭圆曲线「低语」现象的发现",
      "note": "AI/ML（PCA、逻辑回归、可解释性）在椭圆曲线数据中检出 murmurations，引导人类形式化该现象。"
    },
    "2603.19215": {
      "label": "解决 Manin 1972 年关于 R-等价的问题",
      "note": "Gemini 3 Deep Think 写出关键引理与定理的严格证明，人类引导与润色；AlphaEvolve 自动搜索有效交点。",
      "open_problem_name": "Manin 关于对角三次曲面 R-等价的问题"
    },
    "2603.28636": {
      "label": "精确解决 Erdős 问题 #650",
      "note": "ChatGPT 提出初始证明策略；Aristotle 补洞并提供 Lean 形式化；人类撰写最终表述。",
      "open_problem_name": "Erdős 问题 #650"
    },
    "erdos_1196": {
      "label": "Erdős #1196（GPT 辅助，公开报道）",
      "note": "本原集问题；常被引用为从「奥赛感」跃入「仍在被研究的开放问题」。",
      "keystone_reason": "GPT 辅助的 Erdős #1196；开放问题波的锚点。"
    },
    "2604.21187": {
      "label": "AI 辅助解决 1982 年 Ramsey 图问题",
      "note": "LLM 写代码找构造、猜想无穷族、产出证明，并在 Lean 中自动形式化。",
      "open_problem_name": "Grinstead–Roberts 1982 关于双重饱和 Ramsey 图的问题"
    },
    "2604.23468": {
      "label": "8 维球堆积的形式化证明",
      "note": "Gauss 自动形式化并完成球堆积定理的 Lean 证明，补充关键证明并完成验证。"
    },
    "2605.00301": {
      "label": "AI 辅助解决多项 Erdős 猜想",
      "note": "AI 为定理 1.1、1.6 生成初证，并协助 1.2–1.4；人类 refinement 与形式化。",
      "keystone_reason": "多项 Erdős 相关 AI 辅助结果的 arXiv 写本。",
      "open_problem_name": "Erdős 问题 #1196"
    },
    "2605.08033": {
      "label": "AI 证明 Coxeter 组合中的猜想",
      "note": "ChatGPT 5.4 Pro 自主证明主定理（定理 1.3），并发现 Hamaker–Reiner 猜想的反例；人类提供笔记与提示。",
      "open_problem_name": "Escobar–Klein–Weigandt 关于 Cohen–Macaulay ASM 簇的猜想"
    },
    "2605.11656": {
      "label": "反证 GCM 猜想",
      "note": "AI 发现显式概率测度反例；人类给出严格证明与验证。",
      "open_problem_name": "高斯完全单调（GCM）猜想"
    },
    "2605.19979": {
      "label": "AI 解决多项组合猜想",
      "note": "AI 自主发现并生成文中全部证明，解决若干开放猜想；人类选题、验证明并润色表述。",
      "open_problem_name": "Defant 等、Hopkins、Sagan–Wilson 的猜想"
    },
    "2605.20527": {
      "label": "AI 辅助证明 L2 稳定 STFT 相位恢复",
      "note": "LLM 先提出错误约化，再 refined 成定理 2.1 的完整证明，并在大量协助下于 Lean 4 自动形式化。",
      "open_problem_name": "STFT 相位恢复的 L2 稳定性"
    },
    "unit_distance": {
      "label": "单位距离猜想被反证（OpenAI 模型）",
      "note": "高可见离散几何里程碑；随后出现人类消化的 arXiv 写本。叙事锚点：「AI 能动摇重大开放问题」。",
      "keystone_reason": "单位距离猜想反证；重大公共里程碑。"
    },
    "2605.20623": {
      "label": "AI 生成新的 PDE 下界证明",
      "note": "QED 自主生成并验证三则定理的完整证明；人类仅提出问题并审阅最终正确性。"
    },
    "2605.20585": {
      "label": "AI 解决 Kollár–Kovács 问题",
      "note": "ChatGPT 5.5 pro 提供一般想法；Rethlas 系统生成具体例子并可能参与证明构造。",
      "open_problem_name": "Kollár–Kovács 问题 1.1"
    },
    "2605.20594": {
      "label": "AI 解决代数几何中的开放问题",
      "note": "ChatGPT 5.5 pro 提供例子与初证；Rethlas 验改证明；作者组装最终论文。",
      "open_problem_name": "Ciliberto 等问题 1.1"
    },
    "2605.22250": {
      "label": "AI 辅助解决 Han–Jiang 问题",
      "note": "ChatGPT Pro 5.5 提出一般构造想法；Rethlas 找到并证明显式反例；作者验证并撰写。",
      "open_problem_name": "Han–Jiang 关于平坦族中 klt 型开性的问题"
    },
    "2605.22052": {
      "label": "AI 发现 Mauri–Moraga 问题的反例",
      "note": "ChatGPT 5.5 pro 生成两个反例；Rethlas 修补一处证明漏洞并给出长验证。",
      "open_problem_name": "Mauri–Moraga 关于 log Calabi–Yau 对的问题"
    },
    "2605.24160": {
      "label": "解决 Crandall 关于 Erdős–Borwein 常数的问题",
      "note": "AI 参与探索与证明发展，建议引理与结构；人类验证并纠正全部细节。",
      "open_problem_name": "Crandall 关于 Erdős–Borwein 常数二进制数字的问题"
    },
    "2605.27563": {
      "label": "量化线性映射的次高斯性：AI 辅助札记",
      "note": "Gemini 3.5 Flash 发现并证明定理 1（良条件协方差下有界映射的次高斯界），并推广到 Hölder 连续函数。",
      "open_problem_name": "Bombari 关于符号量化线性映射次高斯性的问题"
    },
    "2605.29151": {
      "label": "AI 辅助证明 Aluffi–Chen–Marcolli 猜想",
      "note": "AI 提出二元变形 F_m(y,t)，改写为交错，并给出严格证明步骤；人类验证、补洞并推广到 FM 空间。",
      "open_problem_name": "Aluffi–Chen–Marcolli 关于 M_{0,n} Poincaré 多项式实根性的猜想"
    },
    "2606.05117": {
      "label": "AI 辅助解决 Andrews–Dhar 分拆问题",
      "note": "AxiomProver 在 Lean 中自主生成并验证等分布定理，并与人类共发现双射；形式验证。",
      "open_problem_name": "Andrews–Dhar 双射证明问题"
    },
    "2606.05438": {
      "label": "填补非凸优化下界中的开放缺口",
      "note": "ChatGPT 5.5 Pro 发现 block-chain 构造并开始校验；作者随后验证明、简化路径并改进表述。",
      "open_problem_name": "高阶光滑非凸优化的最优一阶 oracle 复杂度"
    },
    "2607.22580": {
      "label": "AI 辅助解决排队论开放问题",
      "note": "GPT-5.5 Pro 生成初证想法与草稿；作者验改、重写严格性，并在 Lean 4 中形式化关键引理。",
      "open_problem_name": "一快两慢服务器排队系统阈值策略的最优性"
    },
    "2606.11773": {
      "label": "OMWU 末次迭代收敛的首次证明",
      "note": "ChatGPT 证明了建立非活跃坐标最优性的缺失引理（引理 9），这是主定理的关键。",
      "open_problem_name": "光滑凸凹鞍点问题中 OMWU 的末次迭代收敛"
    },
    "2606.15159": {
      "label": "解决 Erdős–Graham ω=2 猜想",
      "note": "Claude 在 Lean 形式化、Python 验证脚本与部分表述上贡献很大；人类主导数学并对内容负责。",
      "open_problem_name": "受限分母埃及分数的 Erdős–Graham 问题（ω=2 情形）"
    },
    "2606.16738": {
      "label": "AI 反证 Elekes–Rónyai 猜想",
      "note": "ChatGPT 5.5 Pro 与 Rethlas 提出路线、找到反例多项式并生成完整证明；人类组织与验证。",
      "keystone_reason": "AI 反证 Elekes–Rónyai 型扩张子猜想。",
      "open_problem_name": "实数上近二次 Elekes–Rónyai 扩张子猜想"
    },
    "2607.22620": {
      "label": "解决 COLT 开放问题",
      "note": "GPT-5.5 Pro 生成证明想法与反例；Claude Code 组装文稿；作者验证与润色。",
      "open_problem_name": "Yun–Sra–Jadbabaie SS–RS–GD 不等式"
    },
    "2606.22636": {
      "label": "解决二进制交换链的 KTV 猜想",
      "note": "ChatGPT 5.5 Pro 生成全部证明策略、技术引理与初证；人类提出问题、引导搜索、评估并在 Lean 中形式化。",
      "open_problem_name": "二进制固定边缘交换链的 KTV 猜想（Kannan–Tetali–Vempala）"
    },
    "2606.22548": {
      "label": "证明孙智伟猜想 3.4",
      "note": "ChatGPT 生成完整证明与初稿；作者独立验证、修改表述，并在 Lean 4 中形式化部分组件。",
      "open_problem_name": "孙智伟猜想 3.4"
    },
    "2606.29593": {
      "label": "AI 解决 SGD 中的开放问题",
      "note": "Gemini 提出泛函分析联系并猜想算子界；ChatGPT 给出初等证明；人类验证。",
      "open_problem_name": "随机 Kaczmarz 最坏情形末次迭代收敛"
    },
    "2606.29687": {
      "label": "机器验证的 FGG 猜想证明",
      "note": "Claude Fable 5 在 Lean 中生成证明，利用编译器反馈与数值检查，闭合开放缺口。",
      "open_problem_name": "FGG 猜想"
    },
    "2607.00708": {
      "label": "解决 Jin–Rubinstein 问题 1.2",
      "note": "AI 生成主定理证明草图与最终文稿；人类验证与润色。",
      "open_problem_name": "Jin–Rubinstein 问题 1.2"
    },
    "2607.01924": {
      "label": "AI 解决拓扑中的开放问题",
      "note": "ChatGPT 5.5 生成主定理完整证明；作者提问、验证正确性并调整表述。",
      "open_problem_name": "Hilbert 球及其亲属的同胚问题"
    },
    "2607.03639": {
      "label": "解决带符号 BAR 唯一性猜想",
      "note": "AI 生成约 150 页证明大纲、做边界层展开并建议关键文献；作者验证并定稿。",
      "open_problem_name": "带符号 BAR 唯一性猜想（Dai–Dieker 开放问题）"
    },
    "2607.04891": {
      "label": "AI 发现 Moraga 猜想的反例",
      "note": "ChatGPT 5.5 pro 生成反例与证明草图；Danus 系统验证并撰写；人类润色。",
      "open_problem_name": "Moraga 关于 Abel p-群作用奇维秩界的猜想"
    },
    "2607.06693": {
      "label": "证明 Calderbank–Daubechies–Freeman–Freeman 猜想",
      "note": "LLM 提出关键概念原则并生成定量证明策略；亦将证明译入 Lean，人类引导显著。",
      "open_problem_name": "独立随机变量稳定相位恢复猜想（CDFF）"
    },
    "2607.20525": {
      "label": "自主反证实数上 sum-product 猜想",
      "note": "AI 在 8 次试验中有 7 次自主给出 sum-product 猜想反证的正确证明；人类验证并准备论文。",
      "keystone_reason": "自主风格反证实数上 sum-product 猜想。",
      "open_problem_name": "实数上的 Erdős–Szemerédi sum-product 猜想"
    },
    "2607.12208": {
      "label": "反证 FDR 控制猜想",
      "note": "GPT-5.6 Pro 生成反例、证明与数值证书；人类验证并撰写终稿。",
      "open_problem_name": "相关双侧高斯检验的 FDR 控制"
    },
    "2607.11376": {
      "label": "AI 形式化 type D ASEP 渐近",
      "note": "Claude / Fable 撰写证明并在 Lean 中形式化；人类验证与指导。",
      "open_problem_name": "超过两个对偶粒子的联合 q-矩塔"
    },
    "2607.14238": {
      "label": "解决在线 Spencer 猜想",
      "note": "AI 给出 T=n 时 O(√n) 在线前缀差异的完整证明，并推广到 Beck–Fiala 与更长视野；人类验证与重写。",
      "open_problem_name": "在线 Spencer 猜想（[8] 猜想 1）"
    },
    "2607.19184": {
      "label": "Batyrev 猜想的反例",
      "note": "AI 协助发现反例（可能通过候选簇或计算建议）；人类验证并证明结果。",
      "open_problem_name": "Batyrev 关于 stringy Hodge 数非负性的猜想"
    },
    "2607.19513": {
      "label": "反证 Deré 猜想",
      "note": "Claude Fable 提供过渡到线性条件的关键想法，并自主证明定理 4.5（反例核心）。",
      "open_problem_name": "Deré 猜想（猜想 1.1）"
    },
    "2607.18619": {
      "label": "解决 Balabdaoui–Wellner 猜想",
      "note": "GPT-5.6 Sol 经迭代尝试生成含关键引理与恒等式的全部证明；作者检查、修改表述并加注。",
      "open_problem_name": "Balabdaoui–Wellner 关于 Chernoff 密度强对数凹性的猜想"
    },
    "2607.21508": {
      "label": "Stanley 与 Monical 猜想的反例",
      "note": "AI 借助 SAT 求解器独立发现两猜想的反例；作者验证并呈现。",
      "open_problem_name": "Stanley 关于无爪图 Schur 正性的猜想"
    },
    "2607.23307": {
      "label": "尖锐薄壳不等式获解决",
      "note": "GPT-5.6 Pro 生成初证与关键三阶矩计算；作者验证、修改与润色。",
      "open_problem_name": "方差猜想（薄壳不等式）"
    },
    "2607.23828": {
      "label": "解决 Monical–Tokcan–Yong 猜想 2.25",
      "note": "Codex 生成均匀偶次幂构造、Dyson 常数项证明与完整证明草稿；作者检查、组织并在 Lean 中形式化。",
      "open_problem_name": "Monical–Tokcan–Yong 猜想 2.25"
    },
    "2607.24528": {
      "label": "解决 Feige 猜想",
      "note": "GPT-5.6 Sol 协助发现与探索证明；作者独立验证全部论证并撰写手稿。",
      "open_problem_name": "Feige 猜想"
    },
    "2607.24483": {
      "label": "黄金尖劈的精确解",
      "note": "AI 搜索极值曲线、起草论证并写 Lean 形式化；人类提供数学洞见与验证。",
      "open_problem_name": "Bellman「迷途于林」问题"
    },
    "2607.23980": {
      "label": "Feige 猜想在 δ≥1 时的解决",
      "note": "ChatGPT 5.6 Pro 发现结合 Vlassis–Thomas 与 Grünbaum 的初证；作者检查、修改并用 Codex 形式化。",
      "open_problem_name": "Feige 猜想"
    },
    "2607.26396": {
      "label": "解决 CMR 关于公共拐点线的开放问题",
      "note": "AI 生成主证明与结果；人类验证与润色。",
      "open_problem_name": "Ciliberto–Miranda–Roé 关于一般三次曲线束公共拐点线数目的问题"
    },
    "2607.26419": {
      "label": "Lukic 猜想的反例",
      "note": "GPT-5.6 构造反例序列并可能识别混合共振机制；作者验证并证明结果。",
      "open_problem_name": "Lukic 猜想"
    },
    "2608.00377": {
      "label": "反证 Schubitope 的 Ehrhart 正性猜想",
      "note": "GPT-5.6 找到反例 Schubitope 并生成 SageMath 验证代码；人类认证结果并撰写论文。",
      "open_problem_name": "Schubitope 的 Ehrhart 正性"
    },
    "2608.01040": {
      "label": "解决 Ehrhart 体积猜想的等式情形",
      "note": "Danus 系统自主完成证明、找到后半机制，并在 3 小时 16 分内产出内部自洽证明；人类提供初始观察与最终验证。",
      "open_problem_name": "Ehrhart 体积猜想（等式情形）"
    },
    "2608.02327": {
      "label": "反证 Connes 刚性猜想",
      "note": "GPT-5.6 Sol、Codex、Danus 等找到主构造并组装预证；作者引导与验证。",
      "open_problem_name": "ICC 性质 (T) 群的 Connes 刚性猜想"
    },
    "2608.02537": {
      "label": "超指数奇圈 Ramsey 数",
      "note": "AI 自主发现并起草证明；人类作者编辑并验证正确性。",
      "open_problem_name": "奇圈多色 Ramsey 数的超指数增长"
    },
    "2608.01673": {
      "label": "格点特征函数的尖锐支撑增长",
      "note": "AI 生成全部数学论证与证明；人类作者验证并承担责任。"
    }
  },
  "phases": {
    "prehistory": "ChatGPT 前的工具期",
    "mass_llm": "大众大模型入场",
    "olympiad_formal": "奥赛与形式系统",
    "research_entry": "研究级进入",
    "open_problem_wave": "开放问题波"
  },
  "subfields": {
    "combinatorics": "组合",
    "optimization": "优化",
    "cs_theory_adjacent": "理论 CS 邻域",
    "probability_stats": "概率统计",
    "dynamical_systems": "动力系统",
    "analysis": "分析",
    "number_theory": "数论",
    "discrete_geometry": "离散几何",
    "algebraic_geometry": "代数几何",
    "graph_theory": "图论",
    "algebra": "代数",
    "mathematical_physics": "数学物理",
    "general_or_multiple": "综合/多领域",
    "topology_geometry": "拓扑几何",
    "convex_geometry": "凸几何",
    "other": "其他"
  }
};
